version: '3'
services:
  haproxy:
    build: haproxy
    volumes: ['./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg']
    ports: ['3000:3000']
    networks:
      - net
  nginx200:
    image: nginx:latest
    volumes: ['./nginx200.conf:/etc/nginx/conf.d/default.conf']
    networks:
      - net
  nginx503:
    image: nginx:latest
    volumes: ['./nginx503.conf:/etc/nginx/conf.d/default.conf']
    networks:
      - net
networks:
  net:
    ipam:
      config:
      - {subnet: 192.168.240.0/24}
